#!/usr/bin/env sh

# Execute Husky hooks
. "$(dirname -- "$0")/_/husky.sh"

# Run Prettier to fix formatting
yarn prettier:fix

# Run ESLint and capture the output
eslint_output=$(yarn eslint . 2>&1)

# Check if there were any ESLint errors
if [ $? -ne 0 ]; then
  # Show a beautiful error message
  cat << "EOF"

        /$$$$$$            /$$                           /$$
       /$$__  $$          | $$                          | $$
      | $$  \ $$ /$$   /$$| $$  /$$$$$$  /$$   /$$      | $$  /$$$$$$   /$$$$$$
      | $$  | $$| $$  | $$| $$ /$$__  $$| $$  | $$      | $$ /$$__  $$ /$$__  $$
      | $$  | $$| $$  | $$| $$| $$$$$$$$| $$  | $$      | $$| $$  \ $$| $$$$$$$$
      | $$  | $$| $$  | $$| $$| $$_____/| $$  | $$      | $$| $$  | $$| $$_____/
      |  $$$$$$/|  $$$$$$/| $$|  $$$$$$$|  $$$$$$$      | $$|  $$$$$$$|  $$$$$$$
       \______/  \______/ |__/ \_______/ \____  $$      |__/ \____  $$ \_______/
                                          /$$  | $$           /$$  \ $$
                                         |  $$$$$$/          |  $$$$$$/
                                          \______/            \______/

  ESLint found some errors in your code. Please fix them before committing.
  Here's the ESLint output for reference:

  $eslint_output

EOF
  exit 1
fi

exit 0
