#!/usr/bin/env sh

# Execute Husky hooks
. "$(dirname -- "$0")/_/husky.sh"

# Run Prettier to fix formatting
yarn prettier:fix
yarn eslint .


# Check if there are any errors in the project
if [ $? -ne 0 ]; then
  echo "Warning: Project has error"
fi
