#!/usr/bin/env sh
# Execute Husky hooks
. "$(dirname -- "$0")/_/husky.sh"

yarn prettier:fix

# Check for lint warnings using ESLint and store the output in a variable
lint_output=$(yarn eslint . 2>&1)

# Print the contents of lint_output for debugging
echo "lint_output: >>>$lint_output<<<"

# No lint warnings? Code is a masterpiece!
if [ -z "$lint_output" ]; then
  echo "🎉 Your code is a work of art! No lint warnings found."
else
  echo "⚠️ Oops! There are ESLint warnings:"
  echo "$lint_output"
fi